# Custom means that it will use the Dockerfile
runtime: custom

# Flex environment required for WebSocket support, which is required for PeerJS.
env: flex

# Limit resources to one instance, one CPU, very little memory or disk.
manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20
