#!/bin/bash -eu
set -o pipefail

readonly PORT=8080

# prebuild to show progress
DIR="$( cd "$( dirname "$0" )" ; pwd -P )"

docker build $DIR

container=$(
	docker build --quiet $DIR |
		xargs docker run -e USE_DATABASE=false --rm --detach --publish $PORT:$PORT
)
cleanup() {
	docker stop $container >/dev/null
}
trap cleanup EXIT

COUNTER=0
TIMEOUT=3000 # 2 min timeout 10 units == 1 sec

while ! curl --silent http://localhost:$PORT >/dev/null
do
	sleep 0.1
  let COUNTER=COUNTER+1
  if [[ "$COUNTER" == "$TIMEOUT" ]]
  then
    break
  fi
done

$@
