#!/bin/bash -eu
set -o pipefail

readonly PORT=8080

container=$(
	docker build --quiet server |
		xargs docker run --rm --detach --publish $PORT:$PORT
)
cleanup() {
	docker stop $container >/dev/null
}
trap cleanup EXIT

while ! curl --silent http://localhost:$PORT >/dev/null
do
	sleep 0.1
done

$@
