name: build
on:
  workflow_call:

jobs:
  build-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node
      - run: pnpm -F discojs run build

  build-lib-node:
    needs: build-lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node
      - run: pnpm -F discojs-node run build

  build-lib-web:
    needs: build-lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node
      - run: pnpm -F discojs-web run build

  build-server:
    needs: build-lib-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node
      - run: pnpm -F server run build

  build-server-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: docker/setup-buildx-action@v4
      - run: docker build .
      - run: |
          docker build --quiet --load . | \
            xargs docker run --detach --publish 8080:8080
          timeout=120
          while ! curl http://localhost:8080
          do
            [ $timeout -eq 0 ] && exit 1
            sleep 1
            timeout=$((timeout - 1))
          done

  build-cli:
    needs: build-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node
      # Build all subprojects to upload all artifacts at once
      - run: pnpm -r run build
      - uses: actions/upload-artifact@v7
        with: { name: all-builds, path: "*/dist" }

  build-webapp:
    needs: build-lib-web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node
      - run: pnpm -F webapp run build

  build-docs-examples:
    needs: build-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node
      - run: pnpm -F server run build
      - run: pnpm run build
        working-directory: docs/examples
