name: deploy-server
on:
  workflow_run:
    workflows: ["lint-test-build"]
    branches: [production]
    types: [completed]

env:
  node_version: 16
  server_url: https://deai-313515.ew.r.appspot.com/

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: npm
          cache-dependency-path: |
            discojs/package-lock.json
            server/package-lock.json

      - run: npm ci
        working-directory: discojs
      - run: npm run build
        working-directory: discojs/discojs-node

      - name: authenticate-to-google-cloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Generate production env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_URL: ${{ secrets.DB_URL }}
          file_name: .env-for-app-yaml
          fail_on_empty: false

      # Until maybe this is merged: https://github.com/google-github-actions/deploy-appengine/pull/294
      - name: prepare app.yaml
        uses: mshick/fast-envsubst@v1
        with:
          env-file: .env-for-app-yaml
          in-file: app.yaml.template
          out-file: app.yaml


      - name: deploy-to-google-cloud
        uses: google-github-actions/deploy-appengine@v0.8.0
        with:
          working_directory: .
          deliverables: app.yaml
          version: prod
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: test
        run: curl "${{ env.server_url }}"
