name: publish
on:
  workflow_run:
    workflows: [lint-test-build]
    branches: [main]
    types: [completed]

env:
  node_version: 16

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: npm
          registry-url: "https://registry.npmjs.org"
      - run: echo now=`date +%Y%m%d%H%M%S` >> "$GITHUB_ENV"
      - run: npm --workspace=./discojs version prerelease --preid=$now
      - name: fix discojs-core version in deps
        run: sed -E "s,(^\s+\"@epfml/discojs-core\":) \"\*\",\1 \"$now\"," package.json
      - run: npm ci
      - run: npm --workspace=./discojs run build
      - run: npm --workspace=./discojs --access public --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: "epfml/disco:latest"
