name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

env:
  node_version: 16

jobs:

  publish-and-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: |
            package-lock.json

      - name: Bump the lib and server version
        run: npm -w @epfml/discojs-node -w @epfml/discojs -w @epfml/disco-server version ${{ inputs.version }}
        working-directory: discojs/discojs-web

      - name: Bump lib dependencies in server
        run: npm -w @epfml/disco-server install @epfml/discojs-node@^${{ inputs.version }} --save

      - name: Build @epfml/discojs, @epfml/discojs-node and @epfml/discojs-server
        run: |
          npm ci
          npm -w discojs -w server run build

      - name: Create version branch
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'bot@users.noreply.github.com'
          git switch -c branch-v${{ inputs.version }}
          git commit -am "publish v${{ inputs.version }}"
          git push -u origin branch-v${{ inputs.version }}

      - name: Write dependencies for @epfml/discojs and @epfml/discojs-node
        run: npx ts-node publish.ts
        working-directory: discojs

      - name: Publish @epfml/discojs
        run: npm publish --access public
        working-directory: discojs/discojs-web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @epfml/discojs-node
        run: npm publish --access public
        working-directory: discojs/discojs-node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @epfml/disco-server
        run: npm publish --access public
        working-directory: server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create version commit and tag
        run: |
          npm i @epfml/discojs-node
          git switch branch-v${{ inputs.version }}
          git add package-lock.json
          git commit -m "v${{ inputs.version }}"
          git tag -a "v${{ inputs.version }}" -m "disco: v${{ inputs.version }}"
          git push
          git push origin v${{ inputs.version }}
        working-directory: server
