name: record-cypress
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  download-datasets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/download-datasets

  record-test-webapp:
    needs: download-datasets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/pull-dataset-artifacts
      - run: npm --workspace=webapp run build
      - run: npm --workspace=webapp run test:unit
      - uses: cypress-io/github-action@v7
        with:
          working-directory: webapp
          install: false
          start: npm start
          wait-on: "http://localhost:8081" # Waits for above
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
        env:
          VITE_SERVER_URL: http://server
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
