name: release

on:
  release:
    types: [created]

env:
  node_version: 16

jobs:
  discojs-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: discojs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ node_version }}
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: discojs-core/package-lock.json
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  discojs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: discojs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ node_version }}
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: discojs/package-lock.json
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  discojs-node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: discojs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ node_version }}
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: discojs-node/package-lock.json
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
