name: release

on:
  release:
    types: [released]

env:
  node_version: 16
  discojs_dir: discojs
  server_dir: server

jobs:

  discojs-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.discojs_dir }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: ${{ env.discojs_dir }}/package-lock.json

      # build dists
      - run: npm ci
      - run: npm run build

      # copy dependencies from discojs to discojs/discojs-node and discojs/discojs-web
      - run: npx ts-node publish.ts

      # publish dist to @epfml/discojs
      - run: npm publish --access public
        working-directory: ${{ env.discojs_dir }}/discojs-web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # publish dist to @epfml/discojs-node
      - run: npm publish --access public
        working-directory: ${{ env.discojs_dir }}/discojs-node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  server-release:
    runs-on: ubuntu-latest
    needs: discojs-release
    defaults:
      run:
        working-directory: ${{ env.server_dir }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: ${{ env.server }}/package-lock.json

      # build dist
      - run: npm ci
      - run: npm run build

      # publish dist to @epfml/disco-server
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
